package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88-dev

import (
	"context"
	"fmt"
	"strings"

	"github.com/magendooro/magento2-go-common/middleware"
	"github.com/magendooro/magento2-store-graphql-go/graph/model"
	"github.com/rs/zerolog/log"
)

// ContactUs is the resolver for the contactUs field.
func (r *mutationResolver) ContactUs(ctx context.Context, input model.ContactUsInput) (*model.ContactUsOutput, error) {
	storeID := middleware.GetStoreID(ctx)
	if !r.Service.IsContactEnabled(storeID) {
		return nil, fmt.Errorf("The contact form is unavailable.")
	}
	if !isValidEmail(input.Email) {
		return nil, fmt.Errorf("The email address is invalid. Verify the email address and try again.")
	}
	if !trimmedNotEmpty(input.Name) {
		return nil, fmt.Errorf("Name field is required.")
	}
	if !trimmedNotEmpty(input.Comment) {
		return nil, fmt.Errorf("Comment field is required.")
	}
	log.Info().Str("email", input.Email).Str("name", input.Name).Msg("contact form submitted (email sending not implemented)")
	result := true
	return &model.ContactUsOutput{Status: result}, nil
}

// StoreConfig is the resolver for the storeConfig field.
func (r *queryResolver) StoreConfig(ctx context.Context) (*model.StoreConfig, error) {
	storeID := middleware.GetStoreID(ctx)
	return r.Service.GetStoreConfig(ctx, storeID)
}

// AvailableStores is the resolver for the availableStores field.
func (r *queryResolver) AvailableStores(ctx context.Context, useCurrentGroup *bool) ([]*model.StoreConfig, error) {
	storeID := middleware.GetStoreID(ctx)
	storeRow, err := r.Service.GetStoreRow(ctx, storeID)
	if err != nil {
		return nil, err
	}
	useGroup := useCurrentGroup != nil && *useCurrentGroup
	return r.Service.GetAvailableStores(ctx, storeRow.WebsiteID, storeRow.GroupID, useGroup)
}

// Countries is the resolver for the countries field.
func (r *queryResolver) Countries(ctx context.Context) ([]*model.Country, error) {
	storeID := middleware.GetStoreID(ctx)
	locale := r.Service.GetLocale(storeID)
	return r.Service.GetCountries(ctx, locale)
}

// Country is the resolver for the country field.
func (r *queryResolver) Country(ctx context.Context, id *string) (*model.Country, error) {
	if id == nil || strings.TrimSpace(*id) == "" {
		return nil, fmt.Errorf("Country \"id\" value should be specified")
	}
	storeID := middleware.GetStoreID(ctx)
	locale := r.Service.GetLocale(storeID)
	c, err := r.Service.GetCountry(ctx, *id, locale)
	if err != nil {
		return nil, err
	}
	if c == nil {
		return nil, fmt.Errorf("The country isn't available")
	}
	return c, nil
}

// Currency is the resolver for the currency field.
func (r *queryResolver) Currency(ctx context.Context) (*model.Currency, error) {
	storeID := middleware.GetStoreID(ctx)
	return r.Service.GetCurrency(ctx, storeID)
}

// CmsPage is the resolver for the cmsPage field.
func (r *queryResolver) CmsPage(ctx context.Context, id *int, identifier *string) (*model.CmsPage, error) {
	storeID := middleware.GetStoreID(ctx)
	return r.Service.GetCmsPage(ctx, storeID, id, identifier)
}

// CmsBlocks is the resolver for the cmsBlocks field.
func (r *queryResolver) CmsBlocks(ctx context.Context, identifiers []*string) (*model.CmsBlocks, error) {
	storeID := middleware.GetStoreID(ctx)
	ids := make([]string, 0, len(identifiers))
	for _, p := range identifiers {
		if p != nil && *p != "" {
			ids = append(ids, *p)
		}
	}
	return r.Service.GetCmsBlocks(ctx, storeID, ids)
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
