package repository

import (
	"context"
	"database/sql"
	"errors"
	"strings"
)

// UrlRow holds a resolved url_rewrite row.
type UrlRow struct {
	EntityType   string
	EntityID     int
	RequestPath  string
	TargetPath   string
	RedirectType int
	StoreID      int
}

// UrlRepository resolves store URLs via the url_rewrite table.
type UrlRepository struct {
	db *sql.DB
}

func NewUrlRepository(db *sql.DB) *UrlRepository {
	return &UrlRepository{db: db}
}

// GetByRequestPath finds a url_rewrite row by request_path for the given store.
func (r *UrlRepository) GetByRequestPath(ctx context.Context, requestPath string, storeID int) (*UrlRow, error) {
	var row UrlRow
	err := r.db.QueryRowContext(ctx, `
		SELECT entity_type, COALESCE(entity_id,0), COALESCE(request_path,''),
		       COALESCE(target_path,''), redirect_type, store_id
		FROM url_rewrite
		WHERE request_path = ? AND store_id = ?
		LIMIT 1`,
		requestPath, storeID,
	).Scan(&row.EntityType, &row.EntityID, &row.RequestPath,
		&row.TargetPath, &row.RedirectType, &row.StoreID)
	if errors.Is(err, sql.ErrNoRows) {
		return nil, nil
	}
	return &row, err
}

// GetByTargetPath finds a url_rewrite row by target_path (reverse lookup).
// Used when the incoming URL is a canonical target path rather than a request path.
func (r *UrlRepository) GetByTargetPath(ctx context.Context, targetPath string, storeID int) (*UrlRow, error) {
	var row UrlRow
	err := r.db.QueryRowContext(ctx, `
		SELECT entity_type, COALESCE(entity_id,0), COALESCE(request_path,''),
		       COALESCE(target_path,''), redirect_type, store_id
		FROM url_rewrite
		WHERE target_path = ? AND store_id = ? AND is_autogenerated = 1
		LIMIT 1`,
		targetPath, storeID,
	).Scan(&row.EntityType, &row.EntityID, &row.RequestPath,
		&row.TargetPath, &row.RedirectType, &row.StoreID)
	if errors.Is(err, sql.ErrNoRows) {
		return nil, nil
	}
	return &row, err
}

// GetProductTypeID returns the type_id (simple/configurable/bundle/virtual/etc.)
// for the given product entity_id. Used to return the correct __typename.
func (r *UrlRepository) GetProductTypeID(ctx context.Context, entityID int) (string, error) {
	var typeID string
	err := r.db.QueryRowContext(ctx,
		`SELECT type_id FROM catalog_product_entity WHERE entity_id = ?`, entityID).
		Scan(&typeID)
	if errors.Is(err, sql.ErrNoRows) {
		return "simple", nil
	}
	return typeID, err
}

// parseURL strips the scheme+host and returns the path component,
// mirroring Magento's AbstractEntityUrl::parseUrl behavior.
func ParseURLPath(raw string) string {
	// Strip query string for path lookup (preserve for relative_url construction)
	path := raw
	if idx := strings.Index(path, "?"); idx >= 0 {
		path = path[:idx]
	}
	// Strip scheme + host if a full URL was passed
	if idx := strings.Index(path, "://"); idx >= 0 {
		path = path[idx+3:]
		if slash := strings.Index(path, "/"); slash >= 0 {
			path = path[slash+1:]
		}
	}
	// Magento strips a single leading slash but preserves the path otherwise
	if len(path) > 1 && path[0] == '/' {
		path = strings.TrimLeft(path, "/")
	}
	return path
}
