// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type RoutableInterface interface {
	IsRoutableInterface()
	GetRelativeURL() *string
	GetRedirectCode() int
	GetType() *URLRewriteEntityTypeEnum
}

// Routing stub for bundle products.
type BundleProduct struct {
	RelativeURL  *string                   `json:"relative_url,omitempty"`
	RedirectCode int                       `json:"redirect_code"`
	Type         *URLRewriteEntityTypeEnum `json:"type,omitempty"`
}

func (BundleProduct) IsRoutableInterface()                    {}
func (this BundleProduct) GetRelativeURL() *string            { return this.RelativeURL }
func (this BundleProduct) GetRedirectCode() int               { return this.RedirectCode }
func (this BundleProduct) GetType() *URLRewriteEntityTypeEnum { return this.Type }

// Routing stub for categories. Full data available from catalog service.
type CategoryTree struct {
	RelativeURL  *string                   `json:"relative_url,omitempty"`
	RedirectCode int                       `json:"redirect_code"`
	Type         *URLRewriteEntityTypeEnum `json:"type,omitempty"`
	UID          *string                   `json:"uid,omitempty"`
}

func (CategoryTree) IsRoutableInterface()                    {}
func (this CategoryTree) GetRelativeURL() *string            { return this.RelativeURL }
func (this CategoryTree) GetRedirectCode() int               { return this.RedirectCode }
func (this CategoryTree) GetType() *URLRewriteEntityTypeEnum { return this.Type }

type CmsBlock struct {
	Identifier *string `json:"identifier,omitempty"`
	Title      *string `json:"title,omitempty"`
	Content    *string `json:"content,omitempty"`
}

type CmsBlocks struct {
	Items []*CmsBlock `json:"items,omitempty"`
}

type CmsPage struct {
	Identifier      *string                   `json:"identifier,omitempty"`
	URLKey          *string                   `json:"url_key,omitempty"`
	Title           *string                   `json:"title,omitempty"`
	Content         *string                   `json:"content,omitempty"`
	ContentHeading  *string                   `json:"content_heading,omitempty"`
	PageLayout      *string                   `json:"page_layout,omitempty"`
	MetaTitle       *string                   `json:"meta_title,omitempty"`
	MetaDescription *string                   `json:"meta_description,omitempty"`
	MetaKeywords    *string                   `json:"meta_keywords,omitempty"`
	RelativeURL     *string                   `json:"relative_url,omitempty"`
	RedirectCode    int                       `json:"redirect_code"`
	Type            *URLRewriteEntityTypeEnum `json:"type,omitempty"`
}

func (CmsPage) IsRoutableInterface()                    {}
func (this CmsPage) GetRelativeURL() *string            { return this.RelativeURL }
func (this CmsPage) GetRedirectCode() int               { return this.RedirectCode }
func (this CmsPage) GetType() *URLRewriteEntityTypeEnum { return this.Type }

// Routing stub for configurable products.
type ConfigurableProduct struct {
	RelativeURL  *string                   `json:"relative_url,omitempty"`
	RedirectCode int                       `json:"redirect_code"`
	Type         *URLRewriteEntityTypeEnum `json:"type,omitempty"`
}

func (ConfigurableProduct) IsRoutableInterface()                    {}
func (this ConfigurableProduct) GetRelativeURL() *string            { return this.RelativeURL }
func (this ConfigurableProduct) GetRedirectCode() int               { return this.RedirectCode }
func (this ConfigurableProduct) GetType() *URLRewriteEntityTypeEnum { return this.Type }

type ContactUsInput struct {
	Email     string  `json:"email"`
	Name      string  `json:"name"`
	Telephone *string `json:"telephone,omitempty"`
	Comment   string  `json:"comment"`
}

type ContactUsOutput struct {
	Status bool `json:"status"`
}

type Country struct {
	ID                      *string   `json:"id,omitempty"`
	TwoLetterAbbreviation   *string   `json:"two_letter_abbreviation,omitempty"`
	ThreeLetterAbbreviation *string   `json:"three_letter_abbreviation,omitempty"`
	FullNameLocale          *string   `json:"full_name_locale,omitempty"`
	FullNameEnglish         *string   `json:"full_name_english,omitempty"`
	AvailableRegions        []*Region `json:"available_regions,omitempty"`
}

type Currency struct {
	BaseCurrencyCode             *string         `json:"base_currency_code,omitempty"`
	BaseCurrencySymbol           *string         `json:"base_currency_symbol,omitempty"`
	DefaultDisplayCurrencyCode   *string         `json:"default_display_currency_code,omitempty"`
	DefaultDisplayCurrencySymbol *string         `json:"default_display_currency_symbol,omitempty"`
	AvailableCurrencyCodes       []*string       `json:"available_currency_codes,omitempty"`
	ExchangeRates                []*ExchangeRate `json:"exchange_rates,omitempty"`
}

// Routing stub for downloadable products.
type DownloadableProduct struct {
	RelativeURL  *string                   `json:"relative_url,omitempty"`
	RedirectCode int                       `json:"redirect_code"`
	Type         *URLRewriteEntityTypeEnum `json:"type,omitempty"`
}

func (DownloadableProduct) IsRoutableInterface()                    {}
func (this DownloadableProduct) GetRelativeURL() *string            { return this.RelativeURL }
func (this DownloadableProduct) GetRedirectCode() int               { return this.RedirectCode }
func (this DownloadableProduct) GetType() *URLRewriteEntityTypeEnum { return this.Type }

// Returned by urlResolver (deprecated). Use route instead.
type EntityURL struct {
	ID           *int                      `json:"id,omitempty"`
	EntityUID    *string                   `json:"entity_uid,omitempty"`
	CanonicalURL *string                   `json:"canonical_url,omitempty"`
	RelativeURL  *string                   `json:"relative_url,omitempty"`
	RedirectCode *int                      `json:"redirect_code,omitempty"`
	Type         *URLRewriteEntityTypeEnum `json:"type,omitempty"`
}

type ExchangeRate struct {
	CurrencyTo *string  `json:"currency_to,omitempty"`
	Rate       *float64 `json:"rate,omitempty"`
}

// Routing stub for grouped products.
type GroupedProduct struct {
	RelativeURL  *string                   `json:"relative_url,omitempty"`
	RedirectCode int                       `json:"redirect_code"`
	Type         *URLRewriteEntityTypeEnum `json:"type,omitempty"`
}

func (GroupedProduct) IsRoutableInterface()                    {}
func (this GroupedProduct) GetRelativeURL() *string            { return this.RelativeURL }
func (this GroupedProduct) GetRedirectCode() int               { return this.RedirectCode }
func (this GroupedProduct) GetType() *URLRewriteEntityTypeEnum { return this.Type }

type Mutation struct {
}

type Query struct {
}

type ReCaptchaConfigOutput struct {
	IsEnabled      bool                    `json:"is_enabled"`
	Configurations *ReCaptchaConfiguration `json:"configurations,omitempty"`
}

type ReCaptchaConfiguration struct {
	ReCaptchaType            ReCaptchaTypeEnum `json:"re_captcha_type"`
	WebsiteKey               string            `json:"website_key"`
	MinimumScore             *float64          `json:"minimum_score,omitempty"`
	BadgePosition            *string           `json:"badge_position,omitempty"`
	Theme                    string            `json:"theme"`
	LanguageCode             *string           `json:"language_code,omitempty"`
	ValidationFailureMessage string            `json:"validation_failure_message"`
	TechnicalFailureMessage  string            `json:"technical_failure_message"`
}

type ReCaptchaConfigurationV3 struct {
	IsEnabled      bool                `json:"is_enabled"`
	WebsiteKey     string              `json:"website_key"`
	MinimumScore   float64             `json:"minimum_score"`
	BadgePosition  string              `json:"badge_position"`
	LanguageCode   *string             `json:"language_code,omitempty"`
	FailureMessage string              `json:"failure_message"`
	Forms          []ReCaptchaFormEnum `json:"forms"`
	Theme          string              `json:"theme"`
}

type Region struct {
	ID   *int    `json:"id,omitempty"`
	Code *string `json:"code,omitempty"`
	Name *string `json:"name,omitempty"`
}

// Fallback routable type for URLs that don't map to a known entity type.
type RoutableURL struct {
	RelativeURL  *string                   `json:"relative_url,omitempty"`
	RedirectCode int                       `json:"redirect_code"`
	Type         *URLRewriteEntityTypeEnum `json:"type,omitempty"`
}

func (RoutableURL) IsRoutableInterface()                    {}
func (this RoutableURL) GetRelativeURL() *string            { return this.RelativeURL }
func (this RoutableURL) GetRedirectCode() int               { return this.RedirectCode }
func (this RoutableURL) GetType() *URLRewriteEntityTypeEnum { return this.Type }

// Routing stub for simple products. Full data available from catalog service.
type SimpleProduct struct {
	RelativeURL  *string                   `json:"relative_url,omitempty"`
	RedirectCode int                       `json:"redirect_code"`
	Type         *URLRewriteEntityTypeEnum `json:"type,omitempty"`
}

func (SimpleProduct) IsRoutableInterface()                    {}
func (this SimpleProduct) GetRelativeURL() *string            { return this.RelativeURL }
func (this SimpleProduct) GetRedirectCode() int               { return this.RedirectCode }
func (this SimpleProduct) GetType() *URLRewriteEntityTypeEnum { return this.Type }

type StoreConfig struct {
	ID                             *int    `json:"id,omitempty"`
	Code                           *string `json:"code,omitempty"`
	StoreCode                      *string `json:"store_code,omitempty"`
	StoreName                      *string `json:"store_name,omitempty"`
	StoreSortOrder                 *int    `json:"store_sort_order,omitempty"`
	IsDefaultStore                 *bool   `json:"is_default_store,omitempty"`
	StoreGroupCode                 *string `json:"store_group_code,omitempty"`
	StoreGroupName                 *string `json:"store_group_name,omitempty"`
	IsDefaultStoreGroup            *bool   `json:"is_default_store_group,omitempty"`
	StoreGroupDefaultStoreCode     *string `json:"store_group_default_store_code,omitempty"`
	WebsiteID                      *int    `json:"website_id,omitempty"`
	WebsiteCode                    *string `json:"website_code,omitempty"`
	WebsiteName                    *string `json:"website_name,omitempty"`
	Locale                         *string `json:"locale,omitempty"`
	Timezone                       *string `json:"timezone,omitempty"`
	WeightUnit                     *string `json:"weight_unit,omitempty"`
	BaseCurrencyCode               *string `json:"base_currency_code,omitempty"`
	DefaultDisplayCurrencyCode     *string `json:"default_display_currency_code,omitempty"`
	BaseURL                        *string `json:"base_url,omitempty"`
	BaseLinkURL                    *string `json:"base_link_url,omitempty"`
	BaseStaticURL                  *string `json:"base_static_url,omitempty"`
	BaseMediaURL                   *string `json:"base_media_url,omitempty"`
	SecureBaseURL                  *string `json:"secure_base_url,omitempty"`
	SecureBaseLinkURL              *string `json:"secure_base_link_url,omitempty"`
	SecureBaseStaticURL            *string `json:"secure_base_static_url,omitempty"`
	SecureBaseMediaURL             *string `json:"secure_base_media_url,omitempty"`
	UseStoreInURL                  *bool   `json:"use_store_in_url,omitempty"`
	DefaultCountry                 *string `json:"default_country,omitempty"`
	CountriesWithRequiredRegion    *string `json:"countries_with_required_region,omitempty"`
	OptionalZipCountries           *string `json:"optional_zip_countries,omitempty"`
	DisplayStateIfOptional         *bool   `json:"display_state_if_optional,omitempty"`
	DefaultTitle                   *string `json:"default_title,omitempty"`
	TitlePrefix                    *string `json:"title_prefix,omitempty"`
	TitleSuffix                    *string `json:"title_suffix,omitempty"`
	DefaultDescription             *string `json:"default_description,omitempty"`
	DefaultKeywords                *string `json:"default_keywords,omitempty"`
	HeadShortcutIcon               *string `json:"head_shortcut_icon,omitempty"`
	HeaderLogoSrc                  *string `json:"header_logo_src,omitempty"`
	LogoWidth                      *int    `json:"logo_width,omitempty"`
	LogoHeight                     *int    `json:"logo_height,omitempty"`
	LogoAlt                        *string `json:"logo_alt,omitempty"`
	Welcome                        *string `json:"welcome,omitempty"`
	Copyright                      *string `json:"copyright,omitempty"`
	Demonotice                     *int    `json:"demonotice,omitempty"`
	ProductURLSuffix               *string `json:"product_url_suffix,omitempty"`
	CategoryURLSuffix              *string `json:"category_url_suffix,omitempty"`
	TitleSeparator                 *string `json:"title_separator,omitempty"`
	ListMode                       *string `json:"list_mode,omitempty"`
	GridPerPageValues              *string `json:"grid_per_page_values,omitempty"`
	ListPerPageValues              *string `json:"list_per_page_values,omitempty"`
	GridPerPage                    *int    `json:"grid_per_page,omitempty"`
	ListPerPage                    *int    `json:"list_per_page,omitempty"`
	CatalogDefaultSortBy           *string `json:"catalog_default_sort_by,omitempty"`
	Front                          *string `json:"front,omitempty"`
	CmsHomePage                    *string `json:"cms_home_page,omitempty"`
	NoRoute                        *string `json:"no_route,omitempty"`
	CmsNoRoute                     *string `json:"cms_no_route,omitempty"`
	CmsNoCookies                   *string `json:"cms_no_cookies,omitempty"`
	ShowCmsBreadcrumbs             *int    `json:"show_cms_breadcrumbs,omitempty"`
	IsGuestCheckoutEnabled         *bool   `json:"is_guest_checkout_enabled,omitempty"`
	IsOnePageCheckoutEnabled       *bool   `json:"is_one_page_checkout_enabled,omitempty"`
	MaxItemsInOrderSummary         *int    `json:"max_items_in_order_summary,omitempty"`
	MinicartDisplay                *bool   `json:"minicart_display,omitempty"`
	MinicartMaxItems               *int    `json:"minicart_max_items,omitempty"`
	CartExpiresInDays              *int    `json:"cart_expires_in_days,omitempty"`
	IsCheckoutAgreementsEnabled    bool    `json:"is_checkout_agreements_enabled"`
	MinimumPasswordLength          *string `json:"minimum_password_length,omitempty"`
	RequiredCharacterClassesNumber *string `json:"required_character_classes_number,omitempty"`
	AutocompleteOnStorefront       *bool   `json:"autocomplete_on_storefront,omitempty"`
	CreateAccountConfirmation      *bool   `json:"create_account_confirmation,omitempty"`
	ContactEnabled                 bool    `json:"contact_enabled"`
}

// Routing stub for virtual products.
type VirtualProduct struct {
	RelativeURL  *string                   `json:"relative_url,omitempty"`
	RedirectCode int                       `json:"redirect_code"`
	Type         *URLRewriteEntityTypeEnum `json:"type,omitempty"`
}

func (VirtualProduct) IsRoutableInterface()                    {}
func (this VirtualProduct) GetRelativeURL() *string            { return this.RelativeURL }
func (this VirtualProduct) GetRedirectCode() int               { return this.RedirectCode }
func (this VirtualProduct) GetType() *URLRewriteEntityTypeEnum { return this.Type }

type ReCaptchaFormEnum string

const (
	ReCaptchaFormEnumPlaceOrder              ReCaptchaFormEnum = "PLACE_ORDER"
	ReCaptchaFormEnumContact                 ReCaptchaFormEnum = "CONTACT"
	ReCaptchaFormEnumCustomerLogin           ReCaptchaFormEnum = "CUSTOMER_LOGIN"
	ReCaptchaFormEnumCustomerForgotPassword  ReCaptchaFormEnum = "CUSTOMER_FORGOT_PASSWORD"
	ReCaptchaFormEnumCustomerCreate          ReCaptchaFormEnum = "CUSTOMER_CREATE"
	ReCaptchaFormEnumCustomerEdit            ReCaptchaFormEnum = "CUSTOMER_EDIT"
	ReCaptchaFormEnumNewsletter              ReCaptchaFormEnum = "NEWSLETTER"
	ReCaptchaFormEnumProductReview           ReCaptchaFormEnum = "PRODUCT_REVIEW"
	ReCaptchaFormEnumSendfriend              ReCaptchaFormEnum = "SENDFRIEND"
	ReCaptchaFormEnumBraintree               ReCaptchaFormEnum = "BRAINTREE"
	ReCaptchaFormEnumResendConfirmationEmail ReCaptchaFormEnum = "RESEND_CONFIRMATION_EMAIL"
)

var AllReCaptchaFormEnum = []ReCaptchaFormEnum{
	ReCaptchaFormEnumPlaceOrder,
	ReCaptchaFormEnumContact,
	ReCaptchaFormEnumCustomerLogin,
	ReCaptchaFormEnumCustomerForgotPassword,
	ReCaptchaFormEnumCustomerCreate,
	ReCaptchaFormEnumCustomerEdit,
	ReCaptchaFormEnumNewsletter,
	ReCaptchaFormEnumProductReview,
	ReCaptchaFormEnumSendfriend,
	ReCaptchaFormEnumBraintree,
	ReCaptchaFormEnumResendConfirmationEmail,
}

func (e ReCaptchaFormEnum) IsValid() bool {
	switch e {
	case ReCaptchaFormEnumPlaceOrder, ReCaptchaFormEnumContact, ReCaptchaFormEnumCustomerLogin, ReCaptchaFormEnumCustomerForgotPassword, ReCaptchaFormEnumCustomerCreate, ReCaptchaFormEnumCustomerEdit, ReCaptchaFormEnumNewsletter, ReCaptchaFormEnumProductReview, ReCaptchaFormEnumSendfriend, ReCaptchaFormEnumBraintree, ReCaptchaFormEnumResendConfirmationEmail:
		return true
	}
	return false
}

func (e ReCaptchaFormEnum) String() string {
	return string(e)
}

func (e *ReCaptchaFormEnum) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ReCaptchaFormEnum(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ReCaptchaFormEnum", str)
	}
	return nil
}

func (e ReCaptchaFormEnum) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ReCaptchaFormEnum) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ReCaptchaFormEnum) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ReCaptchaTypeEnum string

const (
	ReCaptchaTypeEnumInvisible   ReCaptchaTypeEnum = "INVISIBLE"
	ReCaptchaTypeEnumRecaptcha   ReCaptchaTypeEnum = "RECAPTCHA"
	ReCaptchaTypeEnumRecaptchaV3 ReCaptchaTypeEnum = "RECAPTCHA_V3"
)

var AllReCaptchaTypeEnum = []ReCaptchaTypeEnum{
	ReCaptchaTypeEnumInvisible,
	ReCaptchaTypeEnumRecaptcha,
	ReCaptchaTypeEnumRecaptchaV3,
}

func (e ReCaptchaTypeEnum) IsValid() bool {
	switch e {
	case ReCaptchaTypeEnumInvisible, ReCaptchaTypeEnumRecaptcha, ReCaptchaTypeEnumRecaptchaV3:
		return true
	}
	return false
}

func (e ReCaptchaTypeEnum) String() string {
	return string(e)
}

func (e *ReCaptchaTypeEnum) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ReCaptchaTypeEnum(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ReCaptchaTypeEnum", str)
	}
	return nil
}

func (e ReCaptchaTypeEnum) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ReCaptchaTypeEnum) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ReCaptchaTypeEnum) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type URLRewriteEntityTypeEnum string

const (
	URLRewriteEntityTypeEnumCmsPage  URLRewriteEntityTypeEnum = "CMS_PAGE"
	URLRewriteEntityTypeEnumProduct  URLRewriteEntityTypeEnum = "PRODUCT"
	URLRewriteEntityTypeEnumCategory URLRewriteEntityTypeEnum = "CATEGORY"
)

var AllURLRewriteEntityTypeEnum = []URLRewriteEntityTypeEnum{
	URLRewriteEntityTypeEnumCmsPage,
	URLRewriteEntityTypeEnumProduct,
	URLRewriteEntityTypeEnumCategory,
}

func (e URLRewriteEntityTypeEnum) IsValid() bool {
	switch e {
	case URLRewriteEntityTypeEnumCmsPage, URLRewriteEntityTypeEnumProduct, URLRewriteEntityTypeEnumCategory:
		return true
	}
	return false
}

func (e URLRewriteEntityTypeEnum) String() string {
	return string(e)
}

func (e *URLRewriteEntityTypeEnum) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = URLRewriteEntityTypeEnum(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid UrlRewriteEntityTypeEnum", str)
	}
	return nil
}

func (e URLRewriteEntityTypeEnum) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *URLRewriteEntityTypeEnum) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e URLRewriteEntityTypeEnum) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
