// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CmsBlock struct {
	Identifier *string `json:"identifier,omitempty"`
	Title      *string `json:"title,omitempty"`
	Content    *string `json:"content,omitempty"`
}

type CmsBlocks struct {
	Items []*CmsBlock `json:"items,omitempty"`
}

type CmsPage struct {
	Identifier      *string `json:"identifier,omitempty"`
	URLKey          *string `json:"url_key,omitempty"`
	Title           *string `json:"title,omitempty"`
	Content         *string `json:"content,omitempty"`
	ContentHeading  *string `json:"content_heading,omitempty"`
	PageLayout      *string `json:"page_layout,omitempty"`
	MetaTitle       *string `json:"meta_title,omitempty"`
	MetaDescription *string `json:"meta_description,omitempty"`
	MetaKeywords    *string `json:"meta_keywords,omitempty"`
}

type ContactUsInput struct {
	Email     string  `json:"email"`
	Name      string  `json:"name"`
	Telephone *string `json:"telephone,omitempty"`
	Comment   string  `json:"comment"`
}

type ContactUsOutput struct {
	Status bool `json:"status"`
}

type Country struct {
	ID                      *string   `json:"id,omitempty"`
	TwoLetterAbbreviation   *string   `json:"two_letter_abbreviation,omitempty"`
	ThreeLetterAbbreviation *string   `json:"three_letter_abbreviation,omitempty"`
	FullNameLocale          *string   `json:"full_name_locale,omitempty"`
	FullNameEnglish         *string   `json:"full_name_english,omitempty"`
	AvailableRegions        []*Region `json:"available_regions,omitempty"`
}

type Currency struct {
	BaseCurrencyCode             *string         `json:"base_currency_code,omitempty"`
	BaseCurrencySymbol           *string         `json:"base_currency_symbol,omitempty"`
	DefaultDisplayCurrencyCode   *string         `json:"default_display_currency_code,omitempty"`
	DefaultDisplayCurrencySymbol *string         `json:"default_display_currency_symbol,omitempty"`
	AvailableCurrencyCodes       []*string       `json:"available_currency_codes,omitempty"`
	ExchangeRates                []*ExchangeRate `json:"exchange_rates,omitempty"`
}

type ExchangeRate struct {
	CurrencyTo *string  `json:"currency_to,omitempty"`
	Rate       *float64 `json:"rate,omitempty"`
}

type Mutation struct {
}

type Query struct {
}

type Region struct {
	ID   *int    `json:"id,omitempty"`
	Code *string `json:"code,omitempty"`
	Name *string `json:"name,omitempty"`
}

type StoreConfig struct {
	ID                             *int    `json:"id,omitempty"`
	Code                           *string `json:"code,omitempty"`
	StoreCode                      *string `json:"store_code,omitempty"`
	StoreName                      *string `json:"store_name,omitempty"`
	StoreSortOrder                 *int    `json:"store_sort_order,omitempty"`
	IsDefaultStore                 *bool   `json:"is_default_store,omitempty"`
	StoreGroupCode                 *string `json:"store_group_code,omitempty"`
	StoreGroupName                 *string `json:"store_group_name,omitempty"`
	IsDefaultStoreGroup            *bool   `json:"is_default_store_group,omitempty"`
	StoreGroupDefaultStoreCode     *string `json:"store_group_default_store_code,omitempty"`
	WebsiteID                      *int    `json:"website_id,omitempty"`
	WebsiteCode                    *string `json:"website_code,omitempty"`
	WebsiteName                    *string `json:"website_name,omitempty"`
	Locale                         *string `json:"locale,omitempty"`
	Timezone                       *string `json:"timezone,omitempty"`
	WeightUnit                     *string `json:"weight_unit,omitempty"`
	BaseCurrencyCode               *string `json:"base_currency_code,omitempty"`
	DefaultDisplayCurrencyCode     *string `json:"default_display_currency_code,omitempty"`
	BaseURL                        *string `json:"base_url,omitempty"`
	BaseLinkURL                    *string `json:"base_link_url,omitempty"`
	BaseStaticURL                  *string `json:"base_static_url,omitempty"`
	BaseMediaURL                   *string `json:"base_media_url,omitempty"`
	SecureBaseURL                  *string `json:"secure_base_url,omitempty"`
	SecureBaseLinkURL              *string `json:"secure_base_link_url,omitempty"`
	SecureBaseStaticURL            *string `json:"secure_base_static_url,omitempty"`
	SecureBaseMediaURL             *string `json:"secure_base_media_url,omitempty"`
	UseStoreInURL                  *bool   `json:"use_store_in_url,omitempty"`
	DefaultCountry                 *string `json:"default_country,omitempty"`
	CountriesWithRequiredRegion    *string `json:"countries_with_required_region,omitempty"`
	OptionalZipCountries           *string `json:"optional_zip_countries,omitempty"`
	DisplayStateIfOptional         *bool   `json:"display_state_if_optional,omitempty"`
	DefaultTitle                   *string `json:"default_title,omitempty"`
	TitlePrefix                    *string `json:"title_prefix,omitempty"`
	TitleSuffix                    *string `json:"title_suffix,omitempty"`
	DefaultDescription             *string `json:"default_description,omitempty"`
	DefaultKeywords                *string `json:"default_keywords,omitempty"`
	HeadShortcutIcon               *string `json:"head_shortcut_icon,omitempty"`
	HeaderLogoSrc                  *string `json:"header_logo_src,omitempty"`
	LogoWidth                      *int    `json:"logo_width,omitempty"`
	LogoHeight                     *int    `json:"logo_height,omitempty"`
	LogoAlt                        *string `json:"logo_alt,omitempty"`
	Welcome                        *string `json:"welcome,omitempty"`
	Copyright                      *string `json:"copyright,omitempty"`
	Demonotice                     *int    `json:"demonotice,omitempty"`
	ProductURLSuffix               *string `json:"product_url_suffix,omitempty"`
	CategoryURLSuffix              *string `json:"category_url_suffix,omitempty"`
	TitleSeparator                 *string `json:"title_separator,omitempty"`
	ListMode                       *string `json:"list_mode,omitempty"`
	GridPerPageValues              *string `json:"grid_per_page_values,omitempty"`
	ListPerPageValues              *string `json:"list_per_page_values,omitempty"`
	GridPerPage                    *int    `json:"grid_per_page,omitempty"`
	ListPerPage                    *int    `json:"list_per_page,omitempty"`
	CatalogDefaultSortBy           *string `json:"catalog_default_sort_by,omitempty"`
	Front                          *string `json:"front,omitempty"`
	CmsHomePage                    *string `json:"cms_home_page,omitempty"`
	NoRoute                        *string `json:"no_route,omitempty"`
	CmsNoRoute                     *string `json:"cms_no_route,omitempty"`
	CmsNoCookies                   *string `json:"cms_no_cookies,omitempty"`
	ShowCmsBreadcrumbs             *int    `json:"show_cms_breadcrumbs,omitempty"`
	IsGuestCheckoutEnabled         *bool   `json:"is_guest_checkout_enabled,omitempty"`
	IsOnePageCheckoutEnabled       *bool   `json:"is_one_page_checkout_enabled,omitempty"`
	MaxItemsInOrderSummary         *int    `json:"max_items_in_order_summary,omitempty"`
	MinicartDisplay                *bool   `json:"minicart_display,omitempty"`
	MinicartMaxItems               *int    `json:"minicart_max_items,omitempty"`
	CartExpiresInDays              *int    `json:"cart_expires_in_days,omitempty"`
	IsCheckoutAgreementsEnabled    bool    `json:"is_checkout_agreements_enabled"`
	MinimumPasswordLength          *string `json:"minimum_password_length,omitempty"`
	RequiredCharacterClassesNumber *string `json:"required_character_classes_number,omitempty"`
	AutocompleteOnStorefront       *bool   `json:"autocomplete_on_storefront,omitempty"`
	CreateAccountConfirmation      *bool   `json:"create_account_confirmation,omitempty"`
	ContactEnabled                 bool    `json:"contact_enabled"`
}
